services:
  shopping.api:
    container_name: shopping.api
    build:
      context: ./Shopping.API
      dockerfile: Dockerfile
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - shopping.db 

  shopping.client:
    container_name: shopping.client  
    build:
      context: ./Shopping.Client
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
    
  shopping.db:
    container_name: shopping.db
    image: mongo
    ports:
      - "27017:27017"