services:
  shopping.api:
    build:
      context: .
      dockerfile: Shopping.API/Dockerfile

  shopping.client:
    build:
      context: .
      dockerfile: Shopping.Client/Dockerfile

  shopping.db:
    image: mongo